version: '3.9'

networks:
  lorderbackend:
    name: lorder-backend

services:

  mysql:
    image: mysql:5.7.22
    container_name: lorderdb
    restart: unless-stopped
    tty: true
    ports:
      - "33306:${DB_PORT}"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      TZ: 'Europe/Helsinki'
      MYSQL_ROOT_PASSWORD: localhostrootpwd
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - lorderbackend

  lorder:
    container_name: lorderphp
    build:
      context: ./
      dockerfile: docker/phpserver/Dockerfile
    env_file:
      - .env
    ports:
      - "7777:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - lorderbackend

volumes:
  myCodeVolume: